### PR TITLE
Update CI and run against 7.2 and 5.6

### PR DESCRIPTION
**Pull request by RedEnchilada**
#12 

Replaces the old CircleCI 1.0 configs with a new 2.0 config, and runs tests against both 7.2 and 5.6.

### CODE REVIEW

**Comment by RedEnchilada** [comment]
!force code review

**Comment by healthlabs-bugman** [comment]
Testing file changes were not found.
Paging @juanmrad to review the front-end work in this pull request!
Paging @jose-ochoa to review the back-end work in this pull request!
Paging @fortoulrodolfo to review the testing work in this pull request!

I couldn't recognize who these files were relevant to:
.circleci/config.yml
.gitignore
.travis.yml
README.md
bin/composer
bin/init_project
bin/install_composer
bin/linux-sed
bin/php
bin/phpunit
circle.yml
circleci/bin/php
circleci/docker/php/Dockerfile
circleci/docker/php/php.ini
docker/php/Dockerfile

**Comment by RedEnchilada** [comment]
!reassign front-end

**Comment by healthlabs-bugman** [comment]
Paging @johnnie502 to review the front-end work in this pull request!

**Comment by RedEnchilada** [comment]
!reassign back-end

**Comment by healthlabs-bugman** [comment]
Paging @Chekote to review the back-end work in this pull request!

**Comment by RedEnchilada** [comment]
!reassign testing

**Comment by healthlabs-bugman** [comment]
Paging @ramsey-medology to review the testing work in this pull request!

**Pull request merged**
