### PR TITLE
Updating CI to CircleCI and Badges to Medology

### PR DESCRIPTION
**Pull request by TaysirTayyab**
# Overview

This fork was set up to run with TravisCI against @TaysirTayyab's account. We need to move this to CircleCI and get it set up against @Medology's account.

# Changes
- moving `travisci/` to `circleci/`
- updating `.travis.yml` to `circle.yml` with appropriate structure changes
- updating `README.md` to use Medology's badges, instead of mine

### CODE REVIEW

**Comment by TaysirTayyab** [comment]
!reassign back-end @Chekote

**Comment by TaysirTayyab** [comment]
@Chekote I need a couple of things to get this going:

1. Add the project to CircleCI
2. Get me the `CODECLIMATE_REPO_TOKEN` so I can submit coverage reports to code climate

**Comment by TaysirTayyab** [comment]
!force code review

**Comment by Chekote** [comment]
1. The project is now on CircleCI.
2. I have added the `CODECLIMATE_REPO_TOKEN` environmental variable.
3. I don't think you need an API key for this project, it's public.
4. There is a Developers team in Code Climate, and developers are in it. But I feel there is something missing here? Do you want me to associate the team with anything?

**Pull request merged**
